### ISSUE TITLE
Extension NOT COMPATIBLE with CiviCRM 5.19.3

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.twingle#15]
Unfortunately, the fix for security issue [CIVI-SA-2019-21](https://civicrm.org/advisory/civi-sa-2019-21-poi-saved-search-and-report-instance-apis) shipped with CiviCRM ``5.19.3`` is incompatible with the way this extension stores its settings. 

**That means, you will lose all settings and cannot store any new ones.**

Until a new version of the extension is released, you can mitigate this issue by applying [THIS PATCH](https://github.com/systopia/civicrm-core/commit/32d371397494105f4b5f3cb054d5017a5f1ff10b.patch) to disable the security fix. But don't forget to undo this once you have upgraded this extension, the fix was there for a reason.

**Comment by jensschuppe** [comment]
f2b94b72e73ad210d4f0aba32f3e65e720912b13 adds an upgrader that converts the serialized settings object into an array and makes sure that settings are not stored as objects anymore.

This upgrader should be run prior to a CiviCRM upgrade to 5.19.3 or with the patch provided by @bjendres applied (which should be un-applied immediately after the Twingle upgrader ran successfully).

Note that accessing the Twingle profile configuration or running an API call the extension provides may already have deleted your Twingle API settings. In this case, in order to safely restore your settings, restore the settings from a backup, and run the Twingle upgrader immediately before anything accesses Twingle profiles.

The (obviously unneccessary) cast to `object` in `CRM_Twingle_Profile::storeProfiles()` resulted from a bogus method signature of `CRM_Core_BAO_Setting::setItem()` which expects the `$value` parameter to be an `object`.
