### ISSUE TITLE
Option to not use Twingle's SEPA mandate reference

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.twingle#24]
Currently, the system accepts the mandate reference as generated by Twingle. While this makes sense in some cases, in some it doesn't. 

Since CiviCRM is going to be collecting the mandate, there is no need to use the Twingle-generated reference. And some organisations would definitely want to stick to their own schema.

**Comment by bjendres** [comment]
@jensschuppe Could you think of a reason this should not be implemented?

**Comment by jensschuppe** [comment]
Since it is only used when payments are submitted using "debit_manual" (in case that's correctly mapped to "sepa" in the Twingle profile), it would make sense to use your own mandate references. Maybe this could be an option to switch in the Twingle API profile.

I'm not sure, however, whether Twingle stores their mandate reference somewhere even when they don't issue the mandate. You'd have to check back with them about that. Worst case being that Twingle stores an incorrect mandate reference and users rely on it.

**Comment by bjendres** [comment]
@pvmaria: What do you think? Can we safely ditch the Twingle generated reference in favour of our own?

**Comment by pvmaria** [comment]
@bjendres Yes, at least I don't see any problem with that but you are the expert :)

**Comment by bjendres** [comment]
Will be released with ``1.2``
