### ISSUE TITLE
Organisations do not end up in donation receipt group

### ISSUE THREAD

**Issue by MarcMichalsky** [systopia/de.systopia.twingle#83]
If a company is also provided in the donation form, the extension creates an additional organisation contact to which the contribution is assigned and establishes a relationship with the person contact.

Unfortunately, in this case only the person and not the organisation under which the payment is booked is added to the donation receipt group. As a result, if you select all members of this group to create donation receipts, none will be issued for the donation made.

This should be easy to fix. I'll see when I can provide a PR.

**Comment by jensschuppe** [comment]
While I agree conceptually, we should make that configurable in order to not break the (bogus - agreed) behavior for people currently using it that way. Eventually, this should add configuration for selecting either the organisation or the individual contact for
* whom to assign the contribution
* whom to assign the membership
* whom to add to the newsletter/receipts/postal groups
